### ISSUE TITLE
Support correct unzipping of IncorrectHeaders.zip

### ISSUE THREAD

**Issue by Coeur** [nmoinvaz/minizip#159]
File with Incorrect Headers:
[IncorrectHeaders.zip](https://github.com/nmoinvaz/minizip/files/1356685/IncorrectHeaders.zip)

Unzipping it is supposed to give a 59 bytes file ending by _Julius Parishy_.

Applications that succeed at unzipping it on macOS:
* /usr/bin/unzip 6.00 of 20 April 2009 succeeds
* Archive Utility 10.10 (81) succeeds
* The Unarchiver 3.11.3 (115) succeeds

Applications that fail at unzipping it on macOS:
* MiniUnz 1.2.0 fails, as resulting file is truncated to 50 bytes and is ending by _Julius_ only. Logs:
>$ ./miniunz IncorrectHeaders.zip 
MiniUnz 1.2.0, demo of zLib + Unz package
more info at https://github.com/nmoinvaz/minizip
>
>IncorrectHeaders.zip opened
creating directory: IncorrectHeaders/
 extracting: IncorrectHeaders/Readme.txt
error -5 with zipfile in unzReadCurrentFile
error -105 with zipfile in unzCloseCurrentFile
error -5 with zipfile in unzGoToNextFile

**Comment by Coeur** [comment]
OK, actually Julius Parishy found a fix for that on May 9, 2012 at https://github.com/ziparchive/ziparchive/issues/16#issuecomment-5579458
>So I think maybe Minizip is using the cached uncompressed sizes in the file (which in both the local header and central directory is noted as 1857, when in fact it should be 1860) while other tools are uncompressing the data manually and getting the size directly from the outputted data.
>
>Yep, seems minizip was setting the available outbuffer size based on the uncompressed size retrieved from the file. Fixing it manually in a hex editor works like it should, and the given file is successfully uncompressed by removing these lines from unzip.c:
>
>     // unzip.c:1721-1724
>     if ((len>pfile_in_zip_read_info->rest_read_uncompressed) &&
>         (!(pfile_in_zip_read_info->raw)))
>         pfile_in_zip_read_info->stream.avail_out =
>         (uInt)pfile_in_zip_read_info->rest_read_uncompressed;

Nowadays, the lines to remove are [L1311-1312](https://github.com/nmoinvaz/minizip/blob/master/unzip.c#L1311):
```
        if (len > s->pfile_in_zip_read->rest_read_uncompressed)
            s->pfile_in_zip_read->stream.avail_out = (uint16_t)s->pfile_in_zip_read->rest_read_uncompressed;
```

**Comment by Coeur** [comment]
Hum, removing those lines is causing other issues.

But changing `s->pfile_in_zip_read->raw` to `1` does work well.

**Comment by nmoinvaz** [comment]
I am pretty sure this is fixed in the dev branch -- except in the case where AES encryption is used because it is necessary to know the full length before hand.

**Comment by Coeur** [comment]
I'll test the dev branch today. Yet, I believe it's fine to have this fix on master before moving to streams from dev, as it will help to determine if there are regressions.

**Comment by Coeur** [comment]
@nmoinvaz , no, it's hardly fixed on dev, see:
>$ ./miniunz IncorrectHeaders.zip 
MiniUnz 1.3.0, demo of zLib + Unz package
more info at https://github.com/nmoinvaz/minizip
>
>Segmentation fault: 11

**Comment by Coeur** [comment]
@nmoinvaz , no, it's not yet fixed on dev:
>$ ./miniunz IncorrectHeaders.zip 
MiniUnz 2.0.0, demo of zLib + Unz package
more info at https://github.com/nmoinvaz/minizip
>
>IncorrectHeaders.zip opened
Creating directory: IncorrectHeaders/
 Extracting: IncorrectHeaders/Readme.txt
Error -1 going to next entry in zip file

And resulting file is truncated to 50 bytes instead of being 59 bytes.

I'll try to analyze how to apply the same fix for dev branch.

**Comment by Coeur** [comment]
Hum, I just realized:
* IncorrectHeaders.zip is 967 bytes
* Readme.txt is 59 bytes

So this sample is terrible... why so much excess in the zip size?

**Comment by Coeur** [comment]
Hum, I just realized:
* IncorrectHeaders.zip is 967 bytes
* Readme.txt is 59 bytes

So this sample is terrible... why so much excess in the zip size, @jparishy?

**Comment by nmoinvaz** [comment]
I think if you change mz_unzip_entry_read to not modify len then it would work, but it could have unintended consequences for other formats.

**Comment by Coeur** [comment]
@nmoinvaz I'm currently unable to find an equivalent fix on dev branch.
But try this:
* download this 7.2 MB zip file: http://cl.ly/0V070c04231h3Q2k2k2Y
* try to uncompress it with miniunz with the fix from #160 (i.e. my Coeur:incorrectHeaders branch) and it will work (plenty files)
* try to uncompress it with miniunz from dev branch and it will fail (one corrupted file)

**Comment by Coeur** [comment]
Oh, you're right, commenting those lines did fix it:
```
    //if (len > unzip->stream_available)
    //    len = (uint32_t)unzip->stream_available;
```

**Comment by Coeur** [comment]
I'll close this, as there is a pull request for it now.
